Release/10
dataiku/dss-plugin-graph-analytics pull request #1
Opened 2020-06-10 16:54 UTC by StanislasGuinel

release/002 is the current version on the plugin store
release/10 is a new version with a custom chart, improved graph analytics recipe and a new graph clustering recipe

2020-10-14 10:25 UTC, du-phan commented on code-env/python/desc.json
> +  "acceptedPythonInterpreters": ["PYTHON35","PYTHON36","PYTHON37"],
py37 is not supported by dss

2020-10-14 11:34 UTC, du-phan requested changes

2020-10-14 11:34 UTC, du-phan commented on code-env/python/desc.json
> +  "acceptedPythonInterpreters": ["PYTHON35","PYTHON36","PYTHON37"],
py37 is not supported by dss

2020-10-14 11:34 UTC, du-phan commented on resource/style.css
> +@import '/static/public/styles/1.0.0/dku-styles.css';
nitpicking, why not putting this directly into `webapps/graph-chart/style.css` ?

2020-10-14 11:34 UTC, du-phan commented on webapps/graph-chart/backend.py
> +        df = dataiku.Dataset(dataset_name).get_dataframe()
Here we are getting the full dataframe. IMO it will be safer to set a a hard threshold in this, it is a custom chart after all, no need to visualize the whole huge dataset

2020-10-14 11:34 UTC, du-phan commented on python-lib/dku_filtering/filtering.py
> +    return df
Directly modify and return an argument of a function (here is `df`) is not a good practice. You can get some nasty bugs when dealing with mutable objects. You can avoid troubles by explicitly doing `df2 = df.copy()` and work on it, not the most optimised approach as you are copying data, but at least everything that's a cleaner start.
Some ref for you on this topic: 
* https://nedbatchelder.com/text/names.html
* https://docs.python.org/3/faq/programming.html#how-do-i-write-a-function-with-output-parameters-call-by-reference
* https://stackoverflow.com/questions/26027694/correct-style-for-python-functions-that-mutate-the-argument
* https://pythonspeed.com/articles/minimizing-copying/

2020-10-14 11:34 UTC, du-phan commented on webapps/graph-chart/webapp.json
> +        "description": "",
A small description will be nice

2020-10-14 13:11 UTC, StanislasGuinel commented on webapps/graph-chart/backend.py
> +        df = dataiku.Dataset(dataset_name).get_dataframe()
fixed in d345e5e

2020-10-14 13:11 UTC, StanislasGuinel commented on resource/style.css
> +@import '/static/public/styles/1.0.0/dku-styles.css';
fix in d345e5e

2020-10-14 13:12 UTC, StanislasGuinel commented on code-env/python/desc.json
> +  "acceptedPythonInterpreters": ["PYTHON35","PYTHON36","PYTHON37"],
only keep py36 as it's the only i have tested, fix in d345e5e

2020-10-14 13:12 UTC, StanislasGuinel commented on webapps/graph-chart/webapp.json
> +        "description": "",
fix in 0c595ac

2020-10-14 13:25 UTC, alexbourret commented on Makefile
> +PLUGIN_VERSION=1.0.0
Could you update the Makefile with the latest one from [plugin-template](https://github.com/dataiku/dss-plugin-template/blob/master/Makefile), this way you don't have the plugin version in 2 places...

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.json
> +            "description": "Rows of the input dataset must have a Source and a Target column.",
Please remove the final dot in the description

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.py
> +        if not params.get(algo_params.get('param_restriction', None), None):
Could the two if be combined ?

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.py
> +df_graph = df[columns]
is it graph_df if we stick to our convention for naming dataframes ? (same remark for df_res, df_output...)

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.py
> +df = input_dataset.get_dataframe()
input_dataset_df ?

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.py
> +# keep only the necessary columns
if you rename `columns` -> `necessary_columns` you'll get something like `graph_df = input_dataset_df[necessary_columns]` instead, which is clear just from reading it

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/clustering-algorithms/recipe.py
> +start = time.time()
`start_time` would make it clearer ?

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/projected-graph-from-bipartite/recipe.py
> +# CREATE_GRAPH_OF = get_recipe_config()['create_graph_of']
leftovers...

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/stats-from-edge-list/recipe.json
> +        "description": "This recipe uses the python NetworkX library to compute graph features for each node from a dataset of relations.",
Final dot

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/stats-from-edge-list/recipe.json
> +            "description": "Rows of the input dataset must have a Source and a Target column.",
Final dot

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/projected-graph-from-bipartite/recipe.py
> +# Creating the Projected graph
Rename `G` into `projected_graph` and save a `#` ?

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/stats-from-edge-list/recipe.py
> +            _cco[e] = i
please name i, c, e and _cco

2020-10-14 13:25 UTC, alexbourret commented on custom-recipes/stats-from-edge-list/recipe.py
> +    cco = pd.Series(_cco, name='connected_component_id').reset_index()
Maybe a named key for `'connected_component_id'` ?

2020-10-14 13:25 UTC, alexbourret commented on python-lib/dku_graph/graph.py
> +        iGraph.add_vertices(i+1)
so what's the value of `i` here ? len(self.nodes) ?

2020-10-14 13:25 UTC, alexbourret commented on python-lib/dku_graph/graph.py
> +            tgt = row[self.target]
`source` and `target` instead of `src` and `tgt` would make the code clearer

2020-10-14 13:25 UTC, alexbourret commented on python-lib/dku_graph/graph.py
> +    def create_graph(self, df):
`input_df` for `df` ?

2020-10-14 13:25 UTC, alexbourret commented on python-lib/dku_graph/graph.py
> +                source_nodes.add(src)
create_graph is big... Could it be shrink by pushing these two if/elif blocks into 2 functions, with a naming making clearer what is being done here ?

2020-10-14 13:25 UTC, alexbourret commented on python-lib/dku_graph/graph.py
> +            df['{}_diff'.format(col)] = df[col] - df[col].shift(1)
`'{}_diff'.format(col)` is reused 6 times inside the loop, you could store it

2020-10-16 13:24 UTC, StanislasGuinel commented on Makefile
> +PLUGIN_VERSION=1.0.0
eb45c4c

2020-10-16 13:24 UTC, StanislasGuinel commented on custom-recipes/clustering-algorithms/recipe.json
> +            "description": "Rows of the input dataset must have a Source and a Target column.",
e6aa8db

2020-10-16 13:24 UTC, StanislasGuinel commented on custom-recipes/stats-from-edge-list/recipe.json
> +        "description": "This recipe uses the python NetworkX library to compute graph features for each node from a dataset of relations.",
e6aa8db

2020-10-16 13:35 UTC, StanislasGuinel commented on custom-recipes/stats-from-edge-list/recipe.py
> +    cco = pd.Series(_cco, name='connected_component_id').reset_index()
i'm not sure to understand what you mean here ?

2020-10-16 13:37 UTC, StanislasGuinel commented on python-lib/dku_graph/graph.py
> +        iGraph.add_vertices(i+1)
good point, it's better to replace i with len(self.nodes)

2020-10-16 14:44 UTC, StanislasGuinel commented on python-lib/dku_graph/graph.py
> +    def create_graph(self, df):
here the code is some kind of lib, so 'input' is not really necessary, the Graph object is a generic way to create a graph from a dataframe

2020-10-22 18:34 UTC, merged